// This file is automatically generated. Do not manually modify
using UnityEngine;
using Sirenix.OdinInspector;

namespace GamePlugins
{
    public class PluginConfig : ScriptableObject
    {
        #if UNITY_EDITOR
        private static string showPluginName = "";
        #endif

    }
}
